all: safe_test

safe_test:
	@echo -e "\x1B[34m############## compiling safe_test ##############\x1B[0m"
	@(cd safe && make)

clean:
	@echo -e "\x1B[34m############## cleaning safe_test ##############\x1B[0m"
	@(cd safe && make clean)
