SRCDIR=$(dir $(abspath $(lastword $(MAKEFILE_LIST))))
LIBDIR=$(abspath $(SRCDIR)/../lib)
BINDIR=$(abspath $(SRCDIR)/../bin)
INCDIR=$(abspath $(SRCDIR)/../include)

ifndef MODULES
MODULES := $(SOURCES:.cpp=.o)
endif

CXX=g++44
CXXFLAGS=-Wall -g -m32 -D_DEBUG_LEVEL_=5 -Iinclude -I$(INCDIR) -I$(SRCDIR)include

all: $(TARGET)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -L$(LIBDIR) -c $*.cpp -o $@

clean:
	rm -f $(MODULES) $(TARGET) *.o
